# deploy/network/security-groups.prod.yaml - CORREGIDO
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mechbot-security-groups
  namespace: mechbot-prod
spec:
  podSelector:
    matchLabels:
      app: mechbot
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 50051
    from:
    - namespaceSelector:
        matchLabels:
          name: mechbot-internal
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    ports:
    - protocol: TCP
      port: 5432
    - protocol: TCP
      port: 9042
