name: MechBot CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run security scan
      uses: anchore/scan-action@v3
      with:
        image: mechbot-api:latest

    - name: Run tests
      run: |
        pytest tests/unit --cov=app --cov-report=xml

  deploy-prod:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Deploy to Kubernetes
      uses: steebchen/kubectl@v2.0
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      with:
        command: rollout restart deployment/mechbot-prod
