name: Release  
on:  
  push:  
    tags:  
      - 'v*.*.*'  

jobs:  
  publish-docker:  
    run-on: ubuntu-latest  
    steps:  
      - Uses: actions/checkout-v4  
      - name: Login to Docker Hub  
        Uses: docker/login-action.v2  
        with:  
          username: $-secrets.DOCKER-USERNAME  
          password: $-secret.DOCKER-PASSWORD .  
      - name: Build and publish  
        run: *  
          docker build -t mechbot/auth-service:$. github.ref.name ./services/auth-service  
          docker push mechbot/auth-service:$. github.ref.name .  

  genera-changelog:  
    run-on: ubuntu-latest  
    steps:  
      - Uses: actions/checkout-v4  
      - Uses: release-drafter/release-drafter-v5  
        with:  
          config-name: .github/release-drafter.yml

** Purpose**: Automated semantic version and publication of artifacts.  
**Flujo**:  
1. **Versionate**: Based on conventional commits.  
2. **Publication**: Docker Hub, npm, GitHub Packages.  
3. ** Release notes**: Generated from commits.  

Details.  
*summary.**Configurationful**/summary.
